### ISSUE TITLE
Homebrew installer documentation is wrong

### ISSUE THREAD

**Issue by dmahmalat** [gardener/gardenctl-v2#102]
**What happened**:
There is no `gardener/tap/gardenctl-v2` in https://github.com/gardener/homebrew-tap.

**What you expected to happen**:
For `brew install gardener/tap/gardenctl-v2` to work as per the readme found here: https://github.com/gardener/gardenctl-v2#installation

Got an error that the formula was not found.

**Enviornment**:
MacOS

**Comment by unmarshall** [comment]
The issue is that there is no formula with the name `gardenctl-v2` in the tap.
`brew tap-info gardener/tap --json                                                                                                                
[
  {
    "name": "gardener/tap",
    "user": "gardener",
    "repo": "tap",
    "path": "/usr/local/Homebrew/Library/Taps/gardener/homebrew-tap",
    "installed": true,
    "official": false,
    "formula_names": [
      "gardener/tap/gardenctl",
      "gardener/tap/gardenlogin"
    ],
    "formula_files": [
      "/usr/local/Homebrew/Library/Taps/gardener/homebrew-tap/gardenctl.rb",
      "/usr/local/Homebrew/Library/Taps/gardener/homebrew-tap/gardenlogin.rb"
    ],
    "cask_tokens": [

    ],
    "cask_files": [

    ],
    "command_files": [

    ],
    "remote": "https://github.com/gardener/homebrew-tap",
    "custom_remote": null,
    "private": false
  }
]`

i initially thought that you might have kept the same formula name and upgraded the version but that was not the case. The best bet is to use curl and install from github release as per the docs

**Comment by petersutter** [comment]
It should be fixed once we release the first version (2.0.0). We already have the workflow in place that will create the formula https://github.com/gardener/homebrew-tap/blob/master/.github/workflows/update-gardenctl-v2.sh
